

spring:
  datasource:
    username: udna60rm69kh6k
    hikari:
      password:p50cba989daa23b79104eb2651b1939dde57495cb2efd39c76ee1ad4558c37293
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ceu9lmqblp8t3q.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d1knv15idkrafc
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 7000
  servlet:
    application-display-name: gestion des invitations
